In [1]:
class extra:
    def __init__(self,name):
        print("Hello {}".format(name)) # print(f"hello {name}")
e=extra("nisha")

Hello nisha


In [2]:
class extra:
    def __init__(self,first,last,age):
        self.firstname=first
        self.lastname=last
        self.age=age
        
    def __str__(self):
         return "{}-{}".format(name,email)
e=extra("Nisha","qureshi",19)
print(str(e))
print()
#before name="Nisha qureshi"
# email="qureshinisha999@gmail.com" and after  kernel restart it will not work becoz
#ther is no name or email variable

NameError: name 'name' is not defined

In [3]:
class extra:
    def __init__(self,first,last,age):
        self.firstname=first
        self.lastname=last
        self.age=age
        self.fullname=self.firstname + self.lastname
        
    def __str__(self):
         return "{}".format(self.fullname)

    def __repr__(self):
        return f"hii {self.firstname} I am so excited that you are here...:) "
    def __add__(self,other):
        return self.age+other.age
e=extra("Nisha","qureshi",19)
e1=extra("Kajal","gupta",18)
print(str(e))
print(e1.__str__())
print(repr(e))
print(e1.__repr__()) # both method are equal for magic or dunder(__)method
print(e+e1)

Nishaqureshi
Kajalgupta
hii Nisha I am so excited that you are here...:) 
hii Kajal I am so excited that you are here...:) 
37


In [4]:
print(int.__add__(2,3))     #-->2+3

5


In [5]:
print('2'.__add__('3'))       #-->string concatenation

23


In [6]:
print(str.__add__("we are"," powerful"))

we are powerful


In [7]:
print("I".__add__(" can do anything..."))

I can do anything...


In [8]:
print(len("nisha"))
print("qureshi".__len__())

5
7


In [9]:
class length:
    def __init__(self,name):
        self.fullname=name
    def __len__(self):
        return len(self.fullname)
l1=length("nisha qureshi")
print(l1.__len__())
print(len(l1))

13
13


In [10]:
name="Nisha qureshi"
print("hello "+name)

hello Nisha qureshi


In [11]:
print("hello",name)

hello Nisha qureshi


In [12]:
print(f"hello {name}")

hello Nisha qureshi


In [13]:
print("hello {}".format(name))

hello Nisha qureshi


In [14]:
print("hello",name,sep=",")

hello,Nisha qureshi


In [15]:
print("hello",name,end=",")

hello Nisha qureshi,

In [16]:
complex()

0j

In [17]:
x=2
y=3
z=4
print(pow(x,y,z))

0


In [18]:
pow(2,3,4)#--->first it will calculate 2**3=8 then 8%4=0

0

In [19]:
pow(5,3,2)#-->5**3=15 then 15%2=1

1

In [20]:
pow(x,y,z).__repr__

<method-wrapper '__repr__' of int object at 0x0000000074836C20>

In [21]:
pow(x,y,z).__repr__()

'0'

In [22]:
pow(x,y)

8

In [23]:
pow(x,y,z).__doc__

"int(x=0) -> integer\nint(x, base=10) -> integer\n\nConvert a number or string to an integer, or return 0 if no arguments\nare given.  If x is a number, return x.__int__().  For floating point\nnumbers, this truncates towards zero.\n\nIf x is not a number or if base is given, then x must be a string,\nbytes, or bytearray instance representing an integer literal in the\ngiven base.  The literal can be preceded by '+' or '-' and be surrounded\nby whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.\nBase 0 means to interpret the base from the string as an integer literal.\n>>> int('0b100', base=0)\n4"

In [24]:
help(pow(x,y))

Help on int object:

class int(object)
 |  int(x=0) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil__(...)
 |      Ceiling of an Integral retur

In [25]:
divmod(2,10)

(0, 2)

In [26]:
divmod(10.0,2)

(5.0, 0.0)

In [27]:
a=divmod(10,2.5) 

In [28]:
a

(4.0, 0.0)

In [29]:
10/3.5

2.857142857142857

In [30]:
10%3.5

3.0

In [31]:
divmod(10,3.5)     #-->divmod(math.floor(10/3.5),10%3.5)

(2.0, 3.0)

In [32]:
getattr(list,"append")

<method 'append' of 'list' objects>

In [33]:
print(getattr(str,"strip"))

<method 'strip' of 'str' objects>


In [34]:
print(getattr(str,"append","none")) #---> none is default if attribute is not found

none


In [35]:
#hasattr is like getattr but it returns only true and false
hasattr(list,"append")     #--> attribute should be in string

True

In [36]:
hasattr(str,"append")

False

In [37]:
# will give hash value of an object
hash('d')

7381680041025190654

In [38]:
hash('how are you')

1932547846948168866

In [39]:
hash(3)

3

In [40]:
# hash value of 19 integer value will be same as that number 
hash(1234567891011121314)

1234567891011121314

In [41]:
# hash value of 20 numbers are different
hash(12345678910111213141)

816463864042743386

In [42]:
hash(1.0)

1

In [43]:
# will give hex value of integers and long
hex(23)

'0x17'

In [44]:
hex(-34)

'-0x22'

In [45]:
import numpy as np
import random
for i in range(10):
    print(random.normalvariate(2,1.3))

-0.8692707687299239
1.301509203165285
3.2654152911072454
2.054221777450589
1.0024536219204818
-0.7291278895671951
0.7446237436582561
0.26173783295386555
0.10539287455405444
2.9130615209807615


In [46]:
#print(dir(np))

In [47]:
import random 


In [48]:
for i in range(10):
    print(np.random.randint(10)) #it starts from 0

9
6
6
5
9
8
9
0
8
9


In [49]:
for i in range(10):
    print(np.random.random()) # doesn't take any argument and returns value from 0 to 1 [0,1)]

0.6323744442597192
0.2642955392110816
0.9638326607975168
0.615436808984606
0.09097480846152639
0.399119544143671
0.923832890610695
0.19569829000345917
0.5821940745654317
0.9186661438641553


In [50]:
for i in range(5):
    print(np.random.uniform())

0.07532082927566564
0.7227587656522734
0.26163559099912825
0.33001664934301267
0.23004811261978542


In [51]:
for i in range(5):
    print(np.random.uniform(2,7))

6.046884807758912
6.86368396954671
3.920741855269887
5.018871695182961
6.850531893386828


In [52]:
for i in range(5):
    print(np.random.normal())

0.2929824926791525
0.11135084194806517
-2.217387177736493
-0.22310015254408816
-0.9266575196178748


In [53]:
for i in range(5):
    print(np.random.normal(23))

22.710652784555503
22.398443522352842
23.868641102660973
22.295734388737642
23.21040851727382


In [54]:
for i in range(5):
    print(np.random.uniform(4))

2.8436428193910155
1.3101989752968013
3.7931340468738055
1.43000711405081
3.6176549800566913


In [55]:
for i in range(5):
    print(np.random.normal(2,5))

0.6492349742819088
-4.8456739165852305
9.440597712703036
-0.811254213487155
4.317685599583287


In [56]:
for i in range(5):
    print(np.random.choice(12)) #it also includes 0

9
9
7
0
1


In [57]:
for i in range(5):
    print(np.random.choice(1,12)) 

[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [58]:
l=[3,4,5,5,6,7,3,12]
for i in range(6):
    random.shuffle(l) # it shuffle or mix whole list this function is only for list and it changes the original list
    print(l)

[12, 5, 4, 6, 7, 3, 5, 3]
[3, 4, 5, 3, 5, 12, 7, 6]
[4, 5, 5, 12, 3, 6, 7, 3]
[7, 6, 5, 3, 12, 4, 5, 3]
[6, 5, 4, 3, 12, 7, 5, 3]
[5, 6, 7, 3, 12, 3, 5, 4]


In [60]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.hist([2,3,4,])
plt.show()

AttributeError: module 'seaborn' has no attribute 'hist'

# Character count program 

In [61]:
s=input()

def char_count(s1):
    w=0
    for i in s1:
        if i != " " and i != "." and i != ",":
            w+=1
        else:
            continue
    return "The string contain {} letters".format(w)
print(char_count(s))


The string contain 0 letters


# counting alphabets

In [62]:
s=input()
def word(s):
    c=len(s)
    for i in s:
        if i==" " or i=="," or i==".":
            c-=1
        else:
            continue
    print("The string contain {} alphabets".format(c))
word(s)        


The string contain 0 alphabets


In [63]:
n1=input()
def word_count(n):
    w=0
    for i in n:
        if i!=" ":
            w+=1
            while j in n[i]:
                j+=1
        else:
            continue
    return w
print(word_count(n1))


0


In [64]:
ascii('a')

"'a'"

In [65]:
ascii('65')

"'65'"

In [66]:
ord('j')

106

In [67]:
chr(65)

'A'

In [68]:
ord('j')

106

In [69]:
ord('J')

74

In [70]:
ord('a')

97

In [71]:
106-97


9

In [72]:
74-65

9

In [73]:
"nisHaqureshi".count('h'and 'H')

1

In [77]:
t="Jupyter notebook"
all_freq=dict()
for i in t:
    if i in all_freq:
        all_freq[i]+=1
    else:
        all_freq[i]=1
for i in range(len(all_freq)):
    print(f"{i}-->{all_freq[i]}")

KeyError: 0