In [2]:
import cv2
# python stores an image in form of numpy arrays and matrix of numbers

In [3]:
img1 = cv2.imread("G:\\nisha\\whatsapp\\example.jpg",1) # read an image in RGB mode
print(img1)


[[[202 177 175]
  [202 177 175]
  [203 175 174]
  ...
  [126  95   0]
  [127  97   0]
  [132 103   0]]

 [[202 177 175]
  [201 176 174]
  [203 175 174]
  ...
  [127  96   0]
  [128  98   0]
  [132 103   0]]

 [[202 177 175]
  [201 176 174]
  [203 175 174]
  ...
  [126  97   0]
  [128 100   0]
  [133 104   0]]

 ...

 [[213 207 208]
  [214 208 209]
  [217 209 209]
  ...
  [ 25  30  31]
  [ 25  31  30]
  [ 27  30  34]]

 [[214 208 209]
  [214 208 209]
  [218 210 210]
  ...
  [ 25  30  31]
  [ 25  31  30]
  [ 27  30  34]]

 [[214 208 209]
  [215 209 210]
  [218 210 210]
  ...
  [ 25  30  31]
  [ 25  31  30]
  [ 27  30  34]]]


In [4]:
img2 = cv2.imread("G:\\nisha\\whatsapp\\e2.jpg",0) # read an image in grayscale
print(img2)

[[18 17 16 ... 20 19 18]
 [18 17 16 ... 18 17 17]
 [18 17 17 ... 16 15 15]
 ...
 [53 52 51 ... 51 51 50]
 [53 52 51 ... 52 52 52]
 [54 52 52 ... 52 52 52]]


In [7]:
img2.shape

(1280, 720)

In [10]:
img2.shape[0]

1280

In [9]:
img2.shape[1]

720

In [10]:
type(img1)

numpy.ndarray

In [11]:
pwd

'C:\\Users\\hp'

In [12]:
img1.shape # it shows 3 channels i.e. RGB color it shows it is a colored image

(956, 865, 3)

In [13]:
img2.shape # black and white image has only a single channel

(1280, 720)

In [2]:
import cv2

img2 = cv2.imread("G:\\nisha\\whatsapp\\e2.jpg",0) # read an image in grayscale
show = cv2.imshow("picture", img2) # here picture is name of the window
e=cv2.waitKey(2000) # it will wait for 2000ms then it will close the window
print(show)

None


In [23]:
cv2.waitKey(0) # when a user press any key then it will automatically close 
                # the window

-1

In [2]:
import cv2

In [3]:
img2 = cv2.imread("G:\\nisha\\whatsapp\\e2.jpg",1) # read an image in grayscale

resized_img = cv2.resize(img2, (600,300))
cv2.imshow("resized image",resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [4]:
cv2.destroyAllWindows()

In [5]:
resize = cv2.resize(img2, (int(img2.shape[1]/2), int(img2.shape[0]/2)))

In [6]:
cv2.imshow("New window", resize)

In [16]:
import cv2

# create a cascade classifier
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

# read an img as it is
img=cv2.imread("G:\\nisha\\whatsapp\\best.jpg")

# reading an image as an grayscale image
gray_img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)
# scale factor decreases the value by 5%

print(type(faces))
print(faces)

for x,y,w,h in faces:
    img3 = cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0), 3)
    
# (0,255,0) --> rgb value of rectangle outline
# 3--> width of rectangle
cv2.imshow("grey", img)

NameError: name 'faces' is not defined

In [7]:
faces

NameError: name 'faces' is not defined

In [9]:
for x,y,w,h in faces:
    img3 = cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0), 3)
    
# (0,255,0) --> rgb value of rectangle outline
# 3--> width of rectangle


NameError: name 'faces' is not defined